import json
import re
import shutil
import zipfile
from pathlib import Path
from urllib.parse import urlparse

from app.services.crawler_service import CrawlerService, normalize_url, sanitize_filename
from app.services.rewrite_service import RewriteService
from app.services.storage_service import StorageService


README_TEMPLATE = """# {project_name}

Cloned from: {source_url}
Generated by cloneX.

## Project Structure

```
{project_name}/
  assets/
    css/       # Stylesheets
    js/        # JavaScript files
    images/    # Image assets
    fonts/     # Font files
    icons/     # Icons and favicons
  pages/       # Crawled HTML pages
  components/  # Reusable components (React export)
  README.md
  package.json
```

## Branding Placeholders

Replace the following placeholders before publishing:

- `{{LOGO}}`
- `{{COMPANY_NAME}}`
- `{{EMAIL}}`
- `{{PHONE}}`
- `{{ADDRESS}}`
- `{{COPYRIGHT}}`

## Usage

For static HTML:

```bash
npx serve pages/
```

For Next.js:

```bash
npm install
npm run dev
```
"""


class ExportService:
    def __init__(self, project_id: str, start_url: str, asset_map: dict, results: dict, replacements: dict):
        self.project_id = project_id
        self.start_url = start_url
        self.asset_map = asset_map
        self.results = results
        self.replacements = replacements
        self.storage = StorageService()
        self.rewriter = RewriteService(start_url, asset_map, replacements)

    def export_html(self) -> str:
        self.storage.write_text(self.project_id, "README.md", self._readme())
        self.storage.write_text(self.project_id, "package.json", self._package_json())

        # Write pages
        for url, result in self.results.items():
            if not result.html:
                continue
            rewritten = self.rewriter.rewrite_html(result.html, url)
            filename = self._page_path(url)
            self.storage.write_text(self.project_id, f"pages/{filename}", rewritten)

        # Copy index page
        start_filename = self._page_path(self.start_url)
        index_html = self.storage.read_text(self.project_id, f"pages/{start_filename}")
        self.storage.write_text(self.project_id, "pages/index.html", index_html)

        return str(self.storage.get_base_path(self.project_id))

    def export_zip(self, output_path: Path) -> Path:
        base = self.storage.get_base_path(self.project_id)
        zip_path = output_path / f"{self.project_id}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file in base.rglob("*"):
                if file.is_file():
                    zf.write(file, file.relative_to(base))
        return zip_path

    def _page_path(self, url: str) -> str:
        parsed = urlparse(url)
        path = parsed.path.strip("/") or "index"
        if not Path(path).suffix:
            path += ".html"
        # Flatten full path to a unique filename to avoid collisions
        filename = path.replace("/", "_")
        filename = re.sub(r"[^a-zA-Z0-9._-]", "_", filename)
        return filename

    def _readme(self) -> str:
        return README_TEMPLATE.format(
            project_name=self.replacements.get("project_name", "cloneX Project"),
            source_url=self.start_url,
        )

    def _package_json(self) -> str:
        return json.dumps(
            {
                "name": self.replacements.get("project_name", "clonex-project"),
                "version": "1.0.0",
                "private": True,
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "start": "next start",
                    "lint": "next lint",
                },
                "dependencies": {
                    "next": "^14.0.0",
                    "react": "^18.3.0",
                    "react-dom": "^18.3.0",
                    "tailwindcss": "^3.4.0",
                    "framer-motion": "^11.0.0",
                },
                "devDependencies": {
                    "@types/node": "^20.0.0",
                    "@types/react": "^18.3.0",
                    "typescript": "^5.4.0",
                    "postcss": "^8.4.0",
                    "autoprefixer": "^10.4.0",
                },
            },
            indent=2,
        )
